The libzmq3 package provided by travis is buggy.
We get the following error message, because libzmq3-dev is incomplete.

/home/travis/build/vrsys/guacamole/src/gua/renderer/video3d_geometry/NetKinectArray.cpp:7:19:
fatal error: zmq.hpp: No such file or directory

I use the workaround mentioned here:

https://github.com/travis-ci/travis-ci/issues/1715